### ISSUE TITLE
Code report when code time is not installed

### ISSUE THREAD

**Issue by AaronKhah92** [swdotcom/swdc-atom-music-time#24]
**Describe the bug**

I got a mail that showed telemtry data e.i a code report from the "Code Time" extension, exept i hadn't installed it, i think you are using the same API for "Music Time", but i think it's wierd and i feel that it is a privacy issue if i get report on data that i didn't sign up to give you. I'm providing a screenshot below.

**ISSUE TYPE**

-   Bug Report

**Expected behavior**

I didn't expect to get that email when I even hadn't installed your "Code Time" extension.

**Screenshots**
https://imgur.com/75mZRez

**Desktop (please complete the following information):**

-   OS: Windows and Ubuntu (dualboot).
-   Plugin version:  Music Time v1.9.7

**Comment by andrewhli** [comment]
Thanks for your feedback @AaronKhah92, and we understand the privacy concern. We are rethinking our APIs and will update you on the resolution

**Comment by andrewhli** [comment]
Hi @AaronKhah92 - We are working to disable Code Time features for Music Time users, who'll be able to enable Code Time from their settings page. Thanks for bringing this to our attention

**Comment by AaronKhah92** [comment]
Thanks for your cooperation @andrewhli , I really appriciate it when a developer listens to it's users. I'm going close this as soon as that disable feature is implemented, so could you let me know here maybe?

**Comment by AaronKhah92** [comment]
@andrewhli Oh, sorry, i missunderstood, i just saw it's already there. Again, thanks :)

**Comment by andrewhli** [comment]
Hi @AaronKhah92 - We've disabled Code Time features for Music Time users unless a user chooses to enable the Code Time features in their settings. You may still see Code Time features in the application because you had joined before we implemented this change. If you do still see Code Time features, feel free toggle "Enable Code Time" to false here: https://app.software.com/settings/profile
